### PR TITLE
Correct for pixel area in Render.py so that images are resolution independent

### PR DESCRIPTION
**Pull request by JBorrow**
This corrects an issue in py-SPHviewer shown in #16 that the surface densities depend on pixel size. Could @AshKelly please confirm that this fixes the issue?

### CODE REVIEW

**Comment by AshKelly** [comment]
Perfect!

resolution_test(1)

**Comment by alejandrobll** [comment]
This was included in earlier versions but I remember it gave problems when the camera was not at the infinity. Could you please check that this returns a sensible answer in that case too?

**Comment by JBorrow** [comment]
It seems fine to me; here's the same test but with r = 0.2, and the box centered at 0.5, 0.5, 0.5:

image

**Comment by alejandrobll** [comment]
I'm sorry for taking so long to review this. 
It is hard to see what you have changed here, but I think is it only dividing by pixel area? If this is the only change, please do it in `get_image()` (there is already a `get_extent()` call that I used for this in a previous revision). If you could please revert your format changes so that git highlights the relevant change only, I will be able to accept your pull request right away. Otherwise, I can make the change myself.

**Comment by alejandrobll** [comment]
This is now merged. Thanks.

**Pull request merged**
